services:
  - name:  dogfood
    url: https://dogfood.styra.com/v1
    credentials:
      bearer:
        scheme: "Styra-Token"
        token: "LQs80PiWNywTPzAAp515QmGm7uvHmUXYglh5t0LutQE"
bundle:
  name: istio/authz
  service: dogfood
  polling:
    min_delay_seconds: 60
    max_delay_seconds: 120

plugins:
  istio_policy_server:
    plugin_addr: ":50051"
    policy_query: "data.istio.authz.allow"
